### PR TITLE
update circlecore to 4.0.2

### PR DESCRIPTION
**Pull request by tybug**
* loading replays from cache is now roughly twice as fast

#75 should be merged after this

### CODE REVIEW

**Comment by tybug** [comment]
#75 will bump to 2.3.0 anyway? this pr doesn't bump

**Comment by InvisibleSymbol** [comment]
oh I thought you wanted to release this before that, but ye we can also just merge #75

**Comment by tybug** [comment]
75 should be turnkey so no reason to wait

**Comment by tybug** [comment]
nvm not quite, need to resolve conflicts, sec

**Pull request merged**
